#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("ClassicPhone.Resource", IsApplication=true)]

namespace ClassicPhone
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues ();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060000
			public const int transparent = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int white = 2131099649;
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int monoandroidsplash = 2130837504;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080001
			public const int logo = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int message = 2131230722;
			
			// aapt resource value: 0x7f080000
			public const int widget = 2131230720;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int monoandroidsplash = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int widget_logo = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int widget_message = 2130903042;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int widget_loading = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int widget_name = 2131034113;
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070001
			public const int BulletPoint = 2131165185;
			
			// aapt resource value: 0x7f070007
			public const int Mono_Android_Theme_Splash = 2131165191;
			
			// aapt resource value: 0x7f070002
			public const int Text = 2131165186;
			
			// aapt resource value: 0x7f070006
			public const int Text_Definition = 2131165190;
			
			// aapt resource value: 0x7f070003
			public const int Text_Loading = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int Text_WordTitle = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int Text_WordType = 2131165189;
			
			// aapt resource value: 0x7f070000
			public const int WidgetBackground = 2131165184;
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int widget_word = 2130968576;
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
